import type { MenuCategory, MenuCategoryName, MenuItem } from "./types.js";

const categoryOrder: MenuCategoryName[] = [
  "Signature Dishes",
  "Artisan Starters",
  "Artisan Pizzas",
  "Sommelier's Selection",
  "Coffee & Brunch",
];

const menuItems: MenuItem[] = [
  {
    id: "dry-aged-ribeye",
    name: "Dry-Aged Ribeye",
    price: 65,
    description: "Forty-day aged ribeye with charred shallot butter and smoked sea salt.",
    category: "Signature Dishes",
    tags: ["Chef's Pick", "Dinner"],
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L7D]tXxu00RkRkWBj?j@00ay~qof",
    inStock: true,
    customizable: true,
  },
  {
    id: "a5-wagyu-strip",
    name: "A5 Wagyu Strip",
    price: 95,
    description: "Seared wagyu striploin with black garlic jus and roasted heirloom carrots.",
    category: "Signature Dishes",
    tags: ["Luxury", "Dinner"],
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L6D]tXxu00RkRkWBj?j@00ay~qof",
    inStock: true,
    customizable: true,
  },
  {
    id: "pan-seared-scallops",
    name: "Pan-Seared Scallops",
    price: 48,
    description: "Golden scallops over cauliflower puree with citrus brown butter.",
    category: "Signature Dishes",
    tags: ["Seafood", "Dinner", "Gluten-Free"],
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L8E{=pof00Rj~qWBj?j@00ay_3of",
    inStock: true,
    customizable: false,
  },
  {
    id: "herb-crusted-lamb",
    name: "Herb-Crusted Lamb",
    price: 72,
    description: "Lamb loin with pistachio herb crust, minted peas, and jus gras.",
    category: "Signature Dishes",
    tags: ["Chef's Pick", "Dinner"],
    imageUrl: "https://images.unsplash.com/photo-1514517220031-1f7d0d2e8a54?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L9F5=pof00Rj~qWBj?j@00ay_3of",
    inStock: true,
    customizable: true,
  },
  {
    id: "truffled-bone-marrow",
    name: "Truffled Bone Marrow",
    price: 28,
    description: "Roasted marrow with sourdough soldiers, parsley salad, and truffle glaze.",
    category: "Artisan Starters",
    tags: ["Starter", "Rich"],
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L9IY0n?b0g%MxuRjM{t7WBj[ofay",
    inStock: true,
    customizable: false,
  },
  {
    id: "heirloom-burrata",
    name: "Heirloom Burrata",
    price: 22,
    description: "Creamy burrata with marinated tomatoes, basil oil, and grilled levain.",
    category: "Artisan Starters",
    tags: ["Vegetarian", "Starter"],
    imageUrl: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L9G@^+_N00M{?boft7Rj~qofayof",
    inStock: true,
    customizable: false,
  },
  {
    id: "smoked-octopus",
    name: "Smoked Octopus",
    price: 32,
    description: "Applewood-smoked octopus with romesco, lemon, and charred fennel.",
    category: "Artisan Starters",
    tags: ["Seafood", "Starter", "Gluten-Free"],
    imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L6F5?^xv00IU-;RjM|t7M{Rjt7of",
    inStock: true,
    customizable: false,
  },
  {
    id: "margherita",
    name: "Margherita",
    price: 16,
    description: "Wood-fired pizza with San Marzano tomato, fior di latte, and basil.",
    category: "Artisan Pizzas",
    tags: ["Vegetarian", "Pizza"],
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L8G@^+xt00xv~qM{M{RjRjRjayof",
    inStock: true,
    customizable: true,
  },
  {
    id: "truffle-arborio",
    name: "Truffle Arborio",
    price: 24,
    description: "White pizza with truffle cream, arborio crisp, fontina, and thyme.",
    category: "Artisan Pizzas",
    tags: ["Vegetarian", "Pizza", "Chef's Pick"],
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L7G@^+Ip00xt~qM{M{RjRjRjayof",
    inStock: false,
    customizable: true,
  },
  {
    id: "wild-mushroom-risotto",
    name: "Wild Mushroom Risotto",
    price: 22,
    description: "Creamy risotto finished with roasted mushrooms, pecorino, and thyme.",
    category: "Artisan Pizzas",
    tags: ["Vegetarian", "Chef's Pick", "Gluten-Free"],
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L5F5?^_300M{_Nt7Rj?b00Rj~qof",
    inStock: true,
    customizable: false,
  },
  {
    id: "barolo-garnet",
    name: "Barolo Garnet",
    price: 18,
    description: "Nebbiolo by the glass with rose, cherry, and cedar notes.",
    category: "Sommelier's Selection",
    tags: ["Wine", "Pairing"],
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L6I=0J0L_N%M~qRjRjof00Rjayof",
    inStock: true,
    customizable: false,
  },
  {
    id: "chateauneuf-du-pape",
    name: "Chateauneuf-du-Pape",
    price: 22,
    description: "Full-bodied Rhone red with dark fruit, garrigue, and pepper.",
    category: "Sommelier's Selection",
    tags: ["Wine", "Pairing"],
    imageUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L5HC1wM{00D%00xv%MRj?bM{Rjof",
    inStock: true,
    customizable: false,
  },
  {
    id: "cremant-dalsace",
    name: "Cremant d'Alsace",
    price: 14,
    description: "Sparkling Alsatian pour with citrus blossom and brioche finish.",
    category: "Sommelier's Selection",
    tags: ["Wine", "Sparkling"],
    imageUrl: "https://images.unsplash.com/photo-1560148218-1a83060f7b32?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L5I=0n00_N%M~qj[ayof00RjWBof",
    inStock: true,
    customizable: false,
  },
  {
    id: "flat-white",
    name: "Flat White",
    price: 5,
    description: "Velvety double-shot espresso with micro-foamed whole milk.",
    category: "Coffee & Brunch",
    tags: ["Coffee", "Brunch"],
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L9L4t+00?b-;_NxvRjRj00M{WBof",
    inStock: true,
    customizable: true,
  },
  {
    id: "oat-flat-white",
    name: "Oat Flat White",
    price: 6,
    description: "House favorite flat white finished with silky oat milk.",
    category: "Coffee & Brunch",
    tags: ["Coffee", "Brunch", "Vegan-Friendly"],
    imageUrl: "https://images.unsplash.com/photo-1534040385115-33dcb3acba5b?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L6L4t+~q00?b-;M{RjRj00M{WBof",
    inStock: true,
    customizable: true,
  },
  {
    id: "avocado-toast",
    name: "Avocado Toast",
    price: 13,
    description: "Seeded sourdough with avocado, citrus labneh, and chili threads.",
    category: "Coffee & Brunch",
    tags: ["Vegetarian", "Brunch"],
    imageUrl: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L7HC1wM{00t7~qM{WBof00RjRjay",
    inStock: true,
    customizable: false,
  },
  {
    id: "blueberry-pancakes",
    name: "Blueberry Pancakes",
    price: 12,
    description: "Buttermilk pancakes with blueberry compote and cultured cream.",
    category: "Coffee & Brunch",
    tags: ["Brunch", "Sweet"],
    imageUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80",
    blurhash: "L7F5?^xv00Rj~qM{M{j[00RjWBay",
    inStock: true,
    customizable: false,
  },
];

export function getMenuItems(): MenuItem[] {
  return menuItems;
}

export function getMenuCategories(): MenuCategory[] {
  return categoryOrder.map((name) => ({
    name,
    items: menuItems.filter((item) => item.category === name),
  }));
}

export function findMenuItemById(itemId: string): MenuItem | undefined {
  return menuItems.find((item) => item.id === itemId);
}
